# My global overrides
border-size=2
border-radius=5


# Time in milliseconds before a notification disappears (5000 = 5 seconds)
default-timeout=4000

# Force every app to follow your timeout, even if the app wants to stay longer
ignore-timeout=1

# Only show 3 notifications at a time; hides the rest in history
max-visible=3

# Wallpaper notification font
[app-name=notify-send]
font=Cantarell Bold 13
format=<span font='Cantarell Bold 13'>%s</span>\n<i><span font='serif 12'>%b</span></i>

[app-name=Waybar]
font=Cantarell Bold 13
format=<span font='Cantarell Bold 13'>%s</span>\n<i><span font='serif 12'>%b</span></i>
